-- Vitória Procurement — Fase 2 / Migração 0010
-- Fornecedores, contatos, dados bancários, categorias e condições de pagamento.
-- (aplicada no projeto gkxglanbkeacilgqggqu — conteúdo idêntico ao executado)
